// src/views/Home.vue
<template>
  <div class="tw-flex tw-w-screen tw-h-screen tw-flex-col">
    <p class="tw-text-5xl tw-text-center tw-my-10 tw-text-cyan-900">
      {{ $t('base.hellow') }}
    </p>
    <div class="tw-flex tw-justify-center">
      <button
        v-for="item in langList"
        :key="item.code"
        class="tw-text-cyan-700 tw-mx-2"
        @click="setLang(item.code)"
      >
        {{ item.text }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { setAppLang } from '@/locales';

const setLang = (lang: string) => {
  setAppLang(lang);
};

const langList = ref([
  {
    text: '中文',
    code: 'zh'
  },
  {
    text: '英文',
    code: 'en'
  },
  {
    text: '日文',
    code: 'ja'
  }
]);
</script>

<style lang="scss"></style>

// src/views/Home.tsx
import { LanguageType, useLanguage } from '@/store/languageStore';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';

const Home = () => {
  const { t } = useTranslation();
  const { changeLanguage } = useLanguage();

  const [langList] = useState([
    {
      text: '中文',
      code: LanguageType.zh
    },
    {
      text: '英文',
      code: LanguageType.en
    },
    {
      text: '日文',
      code: LanguageType.ja
    }
  ]);
  return (
    <>
      <div className="tw-flex tw-w-screen tw-h-screen tw-flex-col">
        <p className="tw-text-5xl tw-text-center tw-my-10 tw-text-cyan-900">
          {t('hello')}
        </p>
        <div className="tw-flex tw-justify-center">
          {langList.map((item) => {
            return (
              <button
                v-for="item in langList"
                key={item.code}
                className="tw-text-cyan-700 tw-mx-2"
                onClick={() => changeLanguage(item.code)}
              >
                {item.text}
              </button>
            );
          })}
        </div>
      </div>
    </>
  );
};

export default Home;
